# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2229f6ce403729de41d141cffc967b3"
application_url = "https://arlie-unloathsome-severely.ngrok-free.dev"
embedded = true
name = "sample-app-demo"
handle = "sample-app-demo-001"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders,read_customers,write_customers,write_script_tags"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://arlie-unloathsome-severely.ngrok-free.dev/auth/callback",
  "https://arlie-unloathsome-severely.ngrok-free.dev/auth/shopify/callback",
  "https://arlie-unloathsome-severely.ngrok-free.dev/api/auth/callback"
]

[pos]
embedded = false
