# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e1dbe67036223d5e04de52864d6605b"
application_url = "https://sample-app-two-sandy.vercel.app"
embedded = true
name = "sample-app-dev"
handle = "sample-app-dev-oo1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders,read_customers,write_customers,write_script_tags"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://sample-app-two-sandy.vercel.app/auth/callback",
  "https://sample-app-two-sandy.vercel.app/auth/shopify/callback",
  "https://sample-app-two-sandy.vercel.app/api/auth/callback"
]

[pos]
embedded = false
